version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: basic-rag-db
    restart: always
    environment:
      POSTGRES_DB: basic_rag
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
